directories:
  output: dist-electron
  buildResources: build
appId: com.juanminigrocery.bizpos
productName: BizPOS
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
extraResources:
  - from: prisma/schema.prisma
    to: prisma/schema.prisma
  - from: migrations
    to: migrations
win:
  target: nsis
  icon: public/icon.ico
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  deleteAppDataOnUninstall: false
  artifactName: BizPOS-Setup-${version}.exe
electronVersion: 43.4.0
